// Frontend/src/routes/auth/register/+page.svelte
<script>
    import { goto } from '$app/navigation';
    import { api } from '$lib/api.js';
    import { t } from '$lib/i18n.js';
    import AppBtn from '$lib/components/AppBtn.svelte';
    import { notify } from '$lib/notify.js';

    let firstName = '';
    let lastName = '';
    let email = '';
    let password = '';
    let passwordConfirm = '';
    let error = '';
    let busy = false;

    async function submit(e) {
        e.preventDefault();
        error = '';
        if (!firstName) { error = $t('auth.reqFirstName'); return; }
        if (!email) { error = $t('auth.reqEmail'); return; }
        if (!password) { error = $t('auth.reqPassword'); return; }
        if (password.length < 6) { error = $t('auth.passwordMin'); return; }
        if (password !== passwordConfirm) { error = $t('auth.passwordMismatch'); return; }
        busy = true;
        try {
            await api('/auth/register', {
                method: 'POST',
                body: JSON.stringify({
                    firstName,
                    lastName: lastName || null,
                    email,
                    password
                })
            });
            notify.success($t('auth.registerSuccess'));
            goto('/auth/login');
        } catch (err) {
            error = err.errors && err.errors.length ? err.errors[0] : (err.message || $t('common.error'));
        } finally {
            busy = false;
        }
    }
</script>

<div class="flex min-h-screen items-center justify-center bg-base-200 p-4">
    <div class="card w-full max-w-sm border border-base-200 bg-base-100 shadow-xl">
        <div class="card-body gap-4">
            <div>
                <h1 class="text-xl font-semibold tracking-tight">{$t('auth.register')}</h1>
                <p class="text-sm text-base-content/50">{$t('auth.registerSubtitle')}</p>
            </div>

            {#if error}
                <div class="alert alert-error text-sm">{error}</div>
            {/if}

            <form onsubmit={submit} class="flex flex-col gap-4">
                <div class="grid grid-cols-2 gap-3">
                    <div class="field">
                        <label class="block text-sm font-semibold mb-1.5 text-base-content" for="reg-first">{$t('auth.firstName')}</label>
                        <input id="reg-first" class="input w-full" type="text" bind:value={firstName} required />
                    </div>
                    <div class="field">
                        <label class="block text-sm font-semibold mb-1.5 text-base-content" for="reg-last">{$t('auth.lastName')}</label>
                        <input id="reg-last" class="input w-full" type="text" bind:value={lastName} />
                    </div>
                </div>
                <div class="field">
                    <label class="block text-sm font-semibold mb-1.5 text-base-content" for="reg-email">{$t('auth.email')}</label>
                    <input id="reg-email" class="input w-full" type="email" bind:value={email} required />
                </div>
                <div class="field">
                    <label class="block text-sm font-semibold mb-1.5 text-base-content" for="reg-pass">{$t('auth.password')}</label>
                    <input id="reg-pass" class="input w-full" type="password" bind:value={password} required />
                </div>
                <div class="field">
                    <label class="block text-sm font-semibold mb-1.5 text-base-content" for="reg-pass2">{$t('auth.passwordConfirm')}</label>
                    <input id="reg-pass2" class="input w-full" type="password" bind:value={passwordConfirm} required />
                </div>
                <AppBtn variant="primary" type="submit" loading={busy}>{$t('auth.register')}</AppBtn>
            </form>

            <p class="text-center text-sm text-base-content/50">
                {$t('auth.haveAccount')}
                <a class="link text-primary" href="/auth/login">{$t('auth.login')}</a>
            </p>
        </div>
    </div>
</div>

// web/src/views/auth/Register.vue
<template>
  <AuthCard
    icon="pi pi-user-plus"
    :subtitle="i18n.t('auth.registerSubtitle')"
    :footer-prompt="i18n.t('auth.haveAccount')"
    :footer-link-text="i18n.t('auth.login')"
    footer-link-route="login"
  >
    <template #messages>
      <Message v-if="errorMessage" severity="error" class="mb-4" :closable="true" @close="errorMessage = ''">
        {{ errorMessage }}
      </Message>
      <Message v-if="successMessage" severity="success" class="mb-4" :closable="true" @close="successMessage = ''">
        {{ successMessage }}
      </Message>
    </template>

    <form @submit.prevent="submit" class="flex flex-col gap-4">
      <div class="grid grid-cols-1 sm:grid-cols-2 gap-4">
        <TextInput
          id="firstName"
          v-model="firstName"
          :label="i18n.t('auth.firstName')"
          autocomplete="given-name"
          :error="firstNameError"
          @blur="firstNameError = firstName.trim() ? '' : i18n.t('auth.reqFirstName')"
        />
        <TextInput
          id="lastName"
          v-model="lastName"
          :label="i18n.t('auth.lastName')"
          autocomplete="family-name"
          :error="lastNameError"
          @blur="lastNameError = lastName.trim() ? '' : i18n.t('auth.reqLastName')"
        />
      </div>

      <TextInput
        id="email"
        v-model="email"
        :label="i18n.t('auth.email')"
        type="email"
        autocomplete="email"
        :error="emailError"
        @blur="emailError = email.trim() ? (emailPattern.test(email.trim()) ? '' : i18n.t('auth.invalidEmail')) : i18n.t('auth.reqEmail')"
      />

      <PasswordInput
        id="password"
        v-model="password"
        :label="i18n.t('auth.password')"
        :error="passwordError"
        @blur="passwordError = password ? (password.length >= 6 ? '' : i18n.t('auth.passwordMin')) : i18n.t('auth.reqPassword')"
      />

      <PasswordInput
        id="confirmPassword"
        v-model="confirmPassword"
        :label="i18n.t('auth.passwordConfirm')"
        :error="confirmError"
        @blur="confirmError = confirmPassword ? (confirmPassword === password ? '' : i18n.t('auth.passwordMismatch')) : i18n.t('auth.reqConfirmPassword')"
      />

      <SubmitButton :label="i18n.t('auth.register')" icon="pi pi-check-circle" :loading="auth.loading" />
    </form>
  </AuthCard>
</template>

<script setup>
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import { useAuthStore } from '../../stores/auth'
import { useI18n } from '../../stores/i18n'
import AuthCard from '../../components/ui/cards/AuthCard.vue'
import TextInput from '../../components/ui/inputs/TextInput.vue'
import PasswordInput from '../../components/ui/inputs/PasswordInput.vue'
import SubmitButton from '../../components/ui/buttons/SubmitButton.vue'

const auth = useAuthStore()
const i18n = useI18n()
const router = useRouter()

const firstName = ref('')
const lastName = ref('')
const email = ref('')
const password = ref('')
const confirmPassword = ref('')

const firstNameError = ref('')
const lastNameError = ref('')
const emailError = ref('')
const passwordError = ref('')
const confirmError = ref('')

const errorMessage = ref('')
const successMessage = ref('')

const emailPattern = /^[^\s@]+@[^\s@]+\.[^\s@]+$/

function validate() {
  firstNameError.value = firstName.value.trim() ? '' : i18n.t('auth.reqFirstName')
  lastNameError.value = lastName.value.trim() ? '' : i18n.t('auth.reqLastName')
  emailError.value = email.value.trim()
    ? emailPattern.test(email.value.trim()) ? '' : i18n.t('auth.invalidEmail')
    : i18n.t('auth.reqEmail')
  passwordError.value = password.value
    ? password.value.length >= 6 ? '' : i18n.t('auth.passwordMin')
    : i18n.t('auth.reqPassword')
  confirmError.value = confirmPassword.value
    ? confirmPassword.value === password.value ? '' : i18n.t('auth.passwordMismatch')
    : i18n.t('auth.reqConfirmPassword')

  return !firstNameError.value && !lastNameError.value && !emailError.value &&
    !passwordError.value && !confirmError.value
}

async function submit() {
  if (!validate()) return

  errorMessage.value = ''
  successMessage.value = ''

  const result = await auth.register({
    firstName: firstName.value.trim(),
    lastName: lastName.value.trim(),
    email: email.value.trim(),
    password: password.value,
  })

  if (result.ok) {
    successMessage.value = i18n.t('auth.registerSuccess')
    setTimeout(() => router.push({ name: 'login' }), 1500)
  } else {
    errorMessage.value = result.message
  }
}
</script>
