// Frontend/src/routes/teacher/dashboard/+page.svelte
<script>
    import { t } from '$lib/i18n.js';
    import { user } from '$lib/auth.js';
    import AppIcon from '$lib/components/AppIcon.svelte';
    import AppPageHead from '$lib/components/AppPageHead.svelte';

    const name = () => ($user ? $user.firstName + ' ' + $user.lastName : '').trim();
    const initials = () => {
        const parts = name().split(/\s+/).filter(Boolean);
        return ((parts[0] || '?')[0] || '') + ((parts[1] || '')[0] || '');
    };

    const STATS = [
        { icon: 'folder', labelKey: 'nav.workspaces', value: 0 },
        { icon: 'students', tone: 'success', labelKey: 'nav.students', value: 0 },
        { icon: 'book', tone: 'warning', labelKey: 'nav.homework', value: 0 }
    ];
</script>

<AppPageHead icon="dashboard">
    <div class="flex items-center gap-3">
        <div class="flex h-10 w-10 items-center justify-center rounded-xl bg-primary text-sm font-bold text-primary-content">{initials()}</div>
        <div>
            <h1 class="text-xl font-semibold tracking-tight">{$t('panel.welcome', { name: name() })}</h1>
            <p class="text-sm text-base-content/50">{$t('role.Teacher')}</p>
        </div>
    </div>
</AppPageHead>

<div class="mt-6 grid gap-4 sm:grid-cols-3">
    {#each STATS as s}
        <div class="card border border-base-200 bg-base-100">
            <div class="card-body flex-row items-center gap-3 py-4">
                <span class="text-primary/60"><AppIcon name={s.icon} class="w-6 h-6" /></span>
                <div>
                    <p class="text-2xl font-bold leading-none">{s.value}</p>
                    <p class="text-sm text-base-content/50">{$t(s.labelKey)}</p>
                </div>
            </div>
        </div>
    {/each}
</div>

<div class="mt-6 card border border-base-200 bg-base-100">
    <div class="card-body">
        <div class="alert alert-info text-sm">{$t('teacher.info')}</div>
    </div>
</div>

// web/src/views/dashboard/Dashboard.vue
<template>
  <div class="space-y-6">
    <!-- Karşılama bandı -->
    <Card class="border-none shadow-lg rounded-2xl overflow-hidden">
      <template #content>
        <div class="bg-gradient-to-r from-primary to-primary-400 p-6 -m-6 mb-0 text-white">
          <div class="flex items-center gap-4">
            <Avatar :label="initials" size="xlarge" shape="circle" class="bg-white/20 text-white" />
            <div>
              <h1 class="text-2xl font-bold m-0">Hoş geldin, {{ auth.fullName }}!</h1>
              <div class="flex items-center gap-2 mt-2">
                <Chip :label="auth.roleName" class="bg-white/20 text-white border-none" />
              </div>
            </div>
          </div>
        </div>
      </template>
    </Card>

    <!-- Stat kartları -->
    <div class="grid grid-cols-1 md:grid-cols-3 gap-6">
      <StatCard icon="pi pi-book" icon-bg-class="bg-primary-50 text-primary" label="Kurslar" :value="0" />
      <StatCard icon="pi pi-users" icon-bg-class="bg-success-50 text-success-600" label="Öğrenciler" :value="0" />
      <StatCard icon="pi pi-file-edit" icon-bg-class="bg-warning-50 text-warning-600" label="Ödevler" :value="0" />
    </div>

    <Card class="border-none shadow rounded-2xl">
      <template #content>
        <Message severity="info" :closable="false">
          Panel özellikleri yakında eklenecek. Şu an auth akışı çalışıyor: giriş, kayıt ve çıkış.
        </Message>
      </template>
    </Card>
  </div>
</template>

<script setup>
import { computed } from 'vue'
import { useAuthStore } from '../../stores/auth'
import StatCard from '../../components/ui/cards/StatCard.vue'

const auth = useAuthStore()

const initials = computed(() => {
  const name = auth.fullName.trim()
  if (!name) return '?'
  const parts = name.split(' ')
  return (parts[0]?.[0] ?? '') + (parts[1]?.[0] ?? '')
})
</script>
